FROM python:3.11-slim

WORKDIR /app

COPY requirements.api.txt ./
RUN pip install --no-cache-dir -r requirements.api.txt

COPY app ./app
COPY cli.py ./cli.py
COPY tests ./tests

CMD ["python", "-m", "uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
